### ISSUE TITLE
Try to configure TailwindCSS in this repository with Add Tailwind CSS to Svelte

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/sveltekit-ssr-tailwindcss-skeleton#1]
I would try to configure TailwindCSS in this repository with [Add Tailwind CSS to Svelte](https://github.com/svelte-add/tailwindcss).

**Comment by stephane-klein** [comment]
My working branch is [`svelte-add`](https://github.com/stephane-klein/sveltekit-ssr-tailwindcss-skeleton/tree/svelte-add)

**Comment by stephane-klein** [comment]
First execution:

```
❯ pnpx svelte-add@latest tailwindcss --tailwindcss-forms --tailwindcss-typography
Packages: +121
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 121, reused 121, downloaded 0, added 121, done
➕ Svelte Add (Version 2023.11.191.00)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.
{
    "type": "Script",
    "start": 0,
    "end": 69,
    "context": "default",
    "content": {
        "type": "Program",
        "start": 58,
        "end": 60,
        "loc": {
            "start": {
                "line": 1,
                "column": 0
            },
            "end": {
                "line": 1,
                "column": 60
            }
        },
        "body": [
            {
                "type": "BlockStatement",
                "start": 58,
                "end": 60,
                "loc": {
                    "start": {
                        "line": 1,
                        "column": 58
                    },
                    "end": {
                        "line": 1,
                        "column": 60
                    }
                },
                "body": []
            }
        ],
        "sourceType": "module"
    }
}
{
    "type": "Script",
    "start": 0,
    "end": 69,
    "context": "default",
    "content": {
        "type": "Program",
        "start": 58,
        "end": 60,
        "loc": {
            "start": {
                "line": 1,
                "column": 0
            },
            "end": {
                "line": 1,
                "column": 60
            }
        },
        "body": [
            {
                "type": "BlockStatement",
                "start": 58,
                "end": 60,
                "loc": {
                    "start": {
                        "line": 1,
                        "column": 58
                    },
                    "end": {
                        "line": 1,
                        "column": 60
                    }
                },
                "body": []
            }
        ],
        "sourceType": "module"
    }
}

Tailwind CSS
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591304/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/update.js:176:21)
    at updateFile (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591304/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/update.js:36:20)
    at async updateJson (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591304/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/update.js:173:2)
    at async run (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591304/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/adders/tailwindcss/__run.js:326:3)
    at async runAdder (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591304/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/index.js:864:2)
    at async main (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591304/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/cli.js:104:4)

Node.js v20.9.0
```

Second execution:

```
$ pnpx svelte-add@latest tailwindcss --tailwindcss-forms --tailwindcss-typography
Packages: +121
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 121, reused 121, downloaded 0, added 121, done
➕ Svelte Add (Version 2023.11.191.00)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

PostCSS
 ✅ already set up! skipping.
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

Tailwind CSS
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591693/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/update.js:176:21)
    at updateFile (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591693/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/update.js:36:20)
    at async updateJson (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591693/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/update.js:173:2)
    at async run (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591693/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/adders/tailwindcss/__run.js:326:3)
    at async runAdder (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591693/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/index.js:864:2)
    at async main (file:///home/stephane/.local/share/pnpm/store/v3/tmp/dlx-591693/node_modules/.pnpm/svelte-add@2023.11.19-1.0/node_modules/svelte-add/cli.js:104:4)

Node.js v20.9.0
```

Git change: https://github.com/stephane-klein/sveltekit-ssr-tailwindcss-skeleton/commit/194c61669682f660e6b1292d035babb44d7b9ee8

**Comment by stephane-klein** [comment]
Todo :

- [ ] Try to fix `SyntaxError: Unexpected end of JSON input`
- [ ] Try to found how to generate `.css` files instead `.pcss`
- [ ] Try to found how to generate `.js` files instead `.cjs`
- [ ] ...
